/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2b451700-9135-464c-a309-5ab14a83d570 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int contadorMovimientos;
  bool movimiento;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"
#include <WiFi.h>
#include <HTTPClient.h>

#define PIR_PIN 27

#define LED1 18
#define LED2 19
#define LED3 21
#define LED4 22

bool estadoAnterior = LOW;

// Reemplaza por la URL de tu Apps Script
String scriptURL = "https://script.google.com/macros/s/AKfycbxOlUMTYOTsaVgFZE5QfI1hxnkBL3tClyGrTEfGwlg878c0xY7KTfCt4bggYa5GcUPH/exec";

void setup() {
  Serial.begin(115200);

delay(1500);

initProperties();

contadorMovimientos = 0;
movimiento = false;

ArduinoCloud.begin(ArduinoIoTPreferredConnection);

setDebugMessageLevel(2);
ArduinoCloud.printDebugInfo();

  pinMode(PIR_PIN, INPUT);

  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);

  digitalWrite(LED1, LOW);
  digitalWrite(LED2, LOW);
  digitalWrite(LED3, LOW);
  digitalWrite(LED4, LOW);

  Serial.println("=== PRUEBA SENSOR HC-SR505 ===");
  Serial.println("Esperando estabilizacion...");
}

void loop()
{
  ArduinoCloud.update();

  int estadoActual = digitalRead(PIR_PIN);

  movimiento = (estadoActual == HIGH);

  if (estadoActual == HIGH)
  {
    digitalWrite(LED1, HIGH);
    digitalWrite(LED2, HIGH);
    digitalWrite(LED3, HIGH);
    digitalWrite(LED4, HIGH);
  }
  else
  {
    digitalWrite(LED1, LOW);
    digitalWrite(LED2, LOW);
    digitalWrite(LED3, LOW);
    digitalWrite(LED4, LOW);
  }

  // Detecta solamente el cambio LOW -> HIGH
  if (estadoActual == HIGH && estadoAnterior == LOW)
  {
    contadorMovimientos++;

    Serial.println("MOVIMIENTO DETECTADO");
    Serial.print("Enviando a Google Sheets: ");
Serial.println(contadorMovimientos);

    enviarAGoogleSheets(contadorMovimientos);
    
  }

  estadoAnterior = estadoActual;

  delay(1000);
}
void enviarAGoogleSheets(int contador)
{
  if (WiFi.status() == WL_CONNECTED)
  {
    HTTPClient http;

    String url = scriptURL + "?contador=" + String(contador);

    http.begin(url);

    int httpCode = http.GET();

    Serial.print("HTTP Response: ");
    Serial.println(httpCode);

    if(httpCode > 0)
    {
      Serial.println("Dato enviado correctamente");
    }
    else
    {
      Serial.println("Error enviando a Google Sheets");
    }

    http.end();
  }
  else
  {
    Serial.println("ESP32 sin conexion WiFi");
  }
}
/*
  Since Movimiento is READ_WRITE variable, onMovimientoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMovimientoChange()  {
  // Add your code here to act upon Movimiento change
}
